apiVersion: v1
kind: Template
metadata:
  name: pipeline
  annotations:
    description: 'This template creates a Build Configuration that uses a Jenkins pipeline
      strategy. '
    iconClass: icon-jenkins
    tags: instant-app,jenkins
parameters:
- name: PROJECT
  description: The name assigned to all of the application objects defined in this template.
  displayName: Application Name
  required: true
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${PROJECT}
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind":
        "DeploymentConfig"}]'
  spec:
    triggers:
    - type: ConfigChange
    source:
      git:
        ref: master
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: launchpad-maven
    annotations:
      openshift.io/display-name: 'Jenkins 2 CentOS 7'
    labels:
      role: jenkins-slave
  spec:
    dockerImageRepository: openshift/jenkins-slave-maven-centos7